In [ ]:
#Assignment_9
# 1. create a random array of shape(6x6) using randint and seed 2
# 2. convert the array a, to identity matrix

In [2]:
import numpy as np

np.random.seed(2)
a = np.random.randint(0,36,(6,6))
print(a)

[[15  8 22 18 11  7]
 [34 31 11 21 31 26]
 [20  3  4 33  3  5]
 [24  4  6 31 19 31]
 [ 2 16 12  4 26 15]
 [ 8 15  8 17 22  9]]


In [7]:
a[:]=np.identity(6)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [9]:
a[:]=np.eye(6)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
