Assignment
Create an array of shape (10, 10) with uint8 random values.
print the shape, size and dimension,
Compute the sum of the third row to the last.
Compute the average of the columns

In [9]:
def array_properties(a):
    print("a = \n", a)
    print("dim = ", a.ndim)
    print("shape = ", a.shape)
    print("datatype = ", a.dtype)
    print("size = ", a.size)
    print()

In [27]:
import numpy as np

#a1 = np.arange(1,13)
#array_properties(a1)

rand = np.random.randint(0,256,(10,10),dtype ='uint8')
array_properties(rand)

print(rand[3:,:])
summation = sum(rand[0,:3])
print("\n\n",summation)


print("\n total: ",len(rand[0,:]))
print("\n sum:",sum(rand[0,:]))     
average = sum(rand[0,:])/len(rand[0,:])
print("\n\n",average)

a = 
 [[ 17  89 254  45  82  37  36 205   5 208]
 [139 128 139 223  38 136 149  42 140  59]
 [174  97  73 121 160 231 143 184  66 199]
 [ 19 215 132 104  17 127 202 125 180 212]
 [222  97  35 193 246  67 217 161  34  90]
 [115 128 249  11 195 208 117  24 143 220]
 [ 96 214 191 211 234  57 251 133  51 177]
 [  2 247 101 167  14 168 229 191 218 155]
 [139 168  20 254   7 218 144  58  43  99]
 [ 83 218  32 108 146 161 126 148 111  60]]
dim =  2
shape =  (10, 10)
datatype =  uint8
size =  100

[[ 19 215 132 104  17 127 202 125 180 212]
 [222  97  35 193 246  67 217 161  34  90]
 [115 128 249  11 195 208 117  24 143 220]
 [ 96 214 191 211 234  57 251 133  51 177]
 [  2 247 101 167  14 168 229 191 218 155]
 [139 168  20 254   7 218 144  58  43  99]
 [ 83 218  32 108 146 161 126 148 111  60]]


 360

 total:  10

 sum: 978


 97.8
